### ISSUE TITLE
Request to add your own website to scrub..

### ISSUE THREAD

**Issue by xXHexaKillXx** [jewbmx/temp_space#1]
Hi just wondering is there a way to add your own source video and scrub it? i am new and would like help or understand

**Comment by jewbmx** [comment]
If your talking about adding a website to the scrapers/providers which give us the list of playable links,  you can simply toss them to me and i will look into adding them. Otherwise its a tinker as you will type of thing lol.

If your talking about adding a playable link of your own, you could show it or a example of it and i can figure that bit out with ya too lol.
